"""empty message

Revision ID: 46e9d33c074
Revises: None
Create Date: 2016-03-10 11:07:19.656011

"""

# revision identifiers, used by Alembic.
revision = '46e9d33c074'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('test', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'test')
    ### end Alembic commands ###
